feat: add IFU functionality
openactive/OpenActive.Server.NET pull request #199
Opened 2023-06-13 17:49 UTC by civsiv

2023-06-30 11:19 UTC, nickevansuk requested changes
In addition to suggested changes previously discussed

2023-06-30 11:19 UTC, nickevansuk commented on Examples/BookingSystem.AspNetCore/Stores/FacilityStore.cs
> +                }
The `FacilityUse` definition seems to be duplicated here? Should we define it as a var above the `if` and then just include it in either case? More maintainable that way

2023-06-30 11:19 UTC, nickevansuk commented on Fakes/OpenActive.FakeDatabase.NET/Models/FacilityUseTable.cs
> +        //}
Great if this isn't required - in which case shall we remove it?
```suggestion
```

2023-07-17 15:25 UTC, lukehesluke commented
As mentioned here: https://github.com/openactive/OpenActive.Server.NET/pull/201#issuecomment-1638371372, this IFU PR includes the changes from https://github.com/openactive/OpenActive.Server.NET/pull/201. So, if this IFUs PR gets merged first, please could the merger then close https://github.com/openactive/OpenActive.Server.NET/pull/201? Thanks

2023-08-02 12:09 UTC, nickevansuk commented
As per this PR's description, a new PR has been created #204 in order to rename the branch to `coverage/ifus`

2023-08-02 12:09 UTC, closed without merging