Coverage/reseller and nobroker role
openactive/OpenActive.Server.NET pull request #74
Opened 2020-10-29 17:13 UTC by NemanjaStefanovic

Added checks for reseller and nobroker role.
I split it up in 2 commits (moving 2 ifs and extending for new checks)

Closes #72

2020-11-05 19:25 UTC, lukehesluke commented
There looks to be one error:

![Screenshot 2020-11-05 at 19 24 34](https://user-images.githubusercontent.com/2067438/98286925-9760e100-1f9c-11eb-8913-f806e3f06203.png)

2021-02-01 15:44 UTC, civsiv commented
Works locally against https://github.com/openactive/openactive-test-suite/pull/293 (however having issues with CI, so not merged)

2021-02-04 13:05 UTC, nickevansuk requested changes
One minor suggestion

2021-02-04 13:05 UTC, nickevansuk commented on OpenActive.Server.NET/CustomBookingEngine/CustomBookingEngine.cs
> +                // Unless it's B when the Broker isn't a ResellerBroker
```suggestion
                // Unless it's B, P or C2 when the Broker isn't a ResellerBroker
```

2021-02-05 15:54 UTC, merged